### ISSUE TITLE
Improvement: Add static checks to github actions

### ISSUE THREAD

**Issue by PhilipMay** [telekom/nlu-bridge#2]
see https://github.com/telekom/HPOflow/blob/main/.github/workflows/static_checks.yml

**Comment by kengelbrecht** [comment]
I have added the in my eyes most important checkers (flake8, black, pydocstyle) with the version tagged v0.2.0. Will add more from your example soon.

**Comment by kengelbrecht** [comment]
@RKirchherr added test for mypy, isort, pylint, mdformat. Closing this now.
