### ISSUE TITLE
Is it intended that this package does not work with Python 3.9?

### ISSUE THREAD

**Issue by PhilipMay** [telekom/nlu-bridge#7]
see

https://github.com/telekom/nlu-bridge/blob/aa7705d0167ca111491b9b6afdc470a21e4f4c0b/pyproject.toml#L19

**Comment by kengelbrecht** [comment]
Yes, this is because Rasa 2 requires python < 3.9, so I thought it would be better to restrict python versions from the beginning to avoid surprises if someone wants to install Rasa on top of an existing installation later. Would be happy to hear your thoughts on this though!

**Comment by PhilipMay** [comment]
That makes sense. Closing this.
